1. Import the libraries
2. Import dataset
3. Preprocess (if required)
4. Modeling
5. Confusion matrix 

In [158]:
# import libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

#### Importing dataset

In [159]:
train = pd.read_csv("C:\Shashank Taneja\Rotman\Winter Term\RSM 8431 Analytics Colloquia\Causal Inference Using Bayesian Network Theory\learning_set.csv", na_values="?")

In [160]:
test = pd.read_csv("C:/Shashank Taneja/Rotman/Winter Term/RSM 8431 Analytics Colloquia/Causal Inference Using Bayesian Network Theory/test_set.csv", na_values="?")

In [161]:
train.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        5.600000e+02       560.000000               560.000000   
mean         1.084014e+06         4.392857                 3.119643   
std          6.710439e+05         2.812435                 3.056704   
min          6.337500e+04         1.000000                 1.000000   
25%          8.782542e+05         2.000000                 1.000000   
50%          1.171752e+06         4.000000                 1.000000   
75%          1.238923e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                560.000000         560.000000   
mean                   3.178571           2.764286   
std                    2.964351           2.816666   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.500000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   560.000000   549.000000       560.000000   
mean                      3.164286     3.553734         3.433929   
std                       2.126957     3.656228         2.473312   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     7.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses  
count       560.000000  560.000000  
mean          2.816071    1.557143  
std           3.013403    1.638191  
min           1.000000    1.000000  
25%           1.000000    1.000000  
50%           1.000000    1.000000  
75%           3.000000    1.000000  
max          10.000000   10.000000

In [162]:
test.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        1.390000e+02       139.000000               139.000000   
mean         1.022111e+06         4.517986                 3.194245   
std          3.146085e+05         2.837003                 3.040494   
min          6.163400e+04         1.000000                 1.000000   
25%          8.335615e+05         2.000000                 1.000000   
50%          1.166654e+06         4.000000                 1.000000   
75%          1.223514e+06         6.000000                 4.500000   
max          1.354840e+06        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                139.000000         139.000000   
mean                   3.323741           2.978417   
std                    3.010166           3.010772   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    6.000000           3.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   139.000000   134.000000       139.000000   
mean                      3.424460     3.507463         3.453237   
std                       2.533767     3.606065         2.300671   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     5.000000         4.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses  
count       139.000000  139.000000  
mean          3.071942    1.719424  
std           3.213739    1.996478  
min           1.000000    1.000000  
25%           1.000000    1.000000  
50%           1.000000    1.000000  
75%           4.000000    1.000000  
max          10.000000   10.000000

#### Preprocessing

In [163]:
#3 Pre-processing
train.isnull().sum()

Sample code number              0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    11
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

In [164]:
test.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    5
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [165]:
# imputing null values with mean
train.fillna(train.mean(), inplace=True)


In [166]:
# imputing null values with mean
test.fillna(test.mean(), inplace=True)


## Modeling
### 1. split X and Y in train and test data
### 2. Fit training data to the logistic regression Modeling

In [167]:
# defining Y values for training set
Y_train = train['Class']

In [168]:
# defining X variables for training set
X_train = train.iloc[:,0:10]

In [169]:
# defining Y values for test set
Y_test = test['Class']

In [170]:
# defining X variables for test set
X_test = test.iloc[:,0:10]

## Fitting data to logistic regression

In [171]:
lr = LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [172]:
Y_pred = lr.predict(X_test)

In [173]:
Y_pred

array(['Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Beni

In [174]:
conf_matrix = confusion_matrix(Y_test, Y_pred)

In [175]:
conf_matrix

array([[88,  0],
       [51,  0]], dtype=int64)

In [176]:
tree = DecisionTreeClassifier()

In [177]:
# fitting the training set to decision tree
tree.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [178]:
Y_predicted = tree.predict(X_test)
Y_predicted

array(['Benign', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Benign', 

In [179]:
#generating confusion matrix
tree_matrix = confusion_matrix(Y_test, Y_predicted)

In [187]:
tree_matrix

array([[86,  2],
       [ 5, 46]], dtype=int64)

In [181]:
tree.score(X_test, Y_test)

0.9496402877697842

In [182]:
# random forest model
from sklearn.ensemble import RandomForestClassifier

In [183]:
model = RandomForestClassifier()

In [184]:
model.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [185]:
Y_forest_pred = model.predict(X_test)
Y_forest_pred

array(['Benign', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Ben

In [186]:
C_matrix = confusion_matrix(Y_test, Y_forest_pred)

In [188]:
C_matrix

array([[87,  1],
       [ 2, 49]], dtype=int64)